### ISSUE TITLE
Delete a Node in Linked List

### ISSUE THREAD

**Issue by niranjana687** [SarthakKeshari/Java-Questions-and-Solutions#80] opened 2021-10-01 10:09 UTC
### Enter your question - 
Delete a Node in Linked List
Write a function to delete a node in a singly-linked list. You will not be given access to the head of the list, instead you will be given access to the node to be deleted directly.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/delete-node-in-a-linked-list/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
linked list

@SarthakKeshari Please assign this to me under hacktoberfest tag!

**Comment by iamsunil25** [comment] 2021-10-01 11:27
@SarthakKeshari Please assign this to me under hacktoberfest tag!

**Comment by SarthakKeshari** [comment] 2021-10-01 12:11
@niranjana687,
Kindly add your solution to "leetcode" folder.
Deadline - 02/10/2021

**Comment by SarthakKeshari** [comment] 2021-10-01 12:11
@iamsunil25,
Kindly don't create PRs before the issue is assigned. And its first come first serve.
So issue will be held by @niranjana687 until the above mentioned deadline.

**Comment by navjotdadwal** [comment] 2021-10-01 15:16
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue

**Closed** 2021-10-02 07:40 UTC
Labels: Level 2, hacktoberfest, Online
